import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1000, height: 700 } });
await page.goto('http://localhost:5173');
await page.waitForSelector('text=Row and Column Operations Calculator');
const rowHandle = page.locator('[data-row-handle="0"]');
const box = await rowHandle.boundingBox();
await page.mouse.move(box.x + box.width/2, box.y + box.height/2);
await page.mouse.down();
await page.waitForTimeout(50);
await page.mouse.up();
await page.waitForTimeout(500);
await page.screenshot({ path: '/tmp/claude-1000/-workspaces-matrix-vibes/aafd3a79-adfe-43b5-9c77-c6143120bb6c/scratchpad/click-test.png' });
console.log(await page.content().then(c => c.includes('Submit')));
await browser.close();
